// Code generated by FTL. DO NOT EDIT.
package pricedb

import (
	"context"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/server"
)

type QueryPricesClient func(context.Context) ([]Price, error)

type SavePriceClient func(context.Context, Price) error

func init() {
	reflection.Register(
		reflection.Database[PriceDatasource]("prices", server.InitMySQL),

		reflection.ProvideResourcesForVerb(
			QueryPrices,
			server.SourceClient[LoadPricesClient, []LoadPricesResult](),
		),

		reflection.ProvideResourcesForVerb(
			SavePrice,
			server.SinkClient[StorePriceClient, StorePriceQuery](),
		),
	)
}
