// Code generated by FTL. DO NOT EDIT.
package pricedb

import (
	"context"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/server"
)

type SavePriceClient func(context.Context, Price) error

func init() {
	reflection.Register(
		reflection.Database[PriceDatasource]("prices", server.InitMySQL),

		reflection.ProvideResourcesForVerb(
			SavePrice,
			server.SinkClient[InsertPriceClient, InsertPriceQuery](),
		),
	)
}
